# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

defaultBaseImage: cgr.dev/chainguard/static:latest-glibc@sha256:5e9c88174a28c259c349f308dd661a6ec61ed5f8c72ecfaefb46cceb811b55a1
