# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

defaultBaseImage: cgr.dev/chainguard/static:latest-glibc@sha256:f0444e0c32aa0d22cca6de79e160306e9f24140fea0ac97c41789ee59814aa87
