# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/kontext:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/kontext/.github/workflows/digest-bot.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
