# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Action Lint

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v3.5.2

      - name: Find yamls
        id: get_yamls
        run: |
          yamls=$(find .github/workflows -name "*.y*ml" | grep -v dependabot.)
          echo "files="${yamls}"" >> $GITHUB_OUTPUT

      - name: Action lint
        uses: reviewdog/action-actionlint@17ea0452ae2cd009a22ca629732a9ce7f49a55e6 # v1.39.0
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}
