# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Action Lint

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Find yamls
        id: get_yamls
        run: |
          yamls=$(find .github/workflows -name "*.y*ml" | grep -v dependabot.)
          echo "files="${yamls}"" >> $GITHUB_OUTPUT

      - name: Action lint
        uses: reviewdog/action-actionlint@52819f5f70db72e17c2fadecd44a791ae4459276 # v1.49.0
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}
