# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Action Lint

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Find yamls
        id: get_yamls
        run: |
          yamls=$(find .github/workflows -name "*.y*ml" | grep -v dependabot.)
          echo "files="${yamls}"" >> $GITHUB_OUTPUT

      - name: Action lint
        uses: reviewdog/action-actionlint@c6ee1eb0a5d47b2af53a203652b5dac0b6c4016e # v1.43.0
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}
