# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # distroles ran on 0 0 * * * lets run this one hour after
    - cron: "0 1 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner }} == 'chainguard-dev'

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - uses: chainguard-dev/octo-sts-action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: digestabot

      - uses: chainguard-dev/digestabot@4298e530896fb4164f9c89030c561b75b9321149 # v1.0.2
        id: digest-bot
        with:
          token: ${{ steps.octo-sts.outputs.token }}

      - run: echo "PR number ${{ steps.digest-bot.outputs.pull_request_number }}"

      - name: Enable auto-merge
        if: ${{ steps.digest-bot.outputs.pull_request_number != '' }}
        run: gh pr merge --auto --squash "https://github.com/${{ github.repository }}/pull/${{ steps.digest-bot.outputs.pull_request_number }}"
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
