# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # distroles ran on 0 0 * * * lets run this one hour after
    - cron: "0 1 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner }} == 'chainguard-dev'

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: chainguard-dev/actions/digesta-bot@main
        id: digest-bot
        with:
          token: ${{ secrets.PULL_REQUEST_AND_CHART_REPO_PAT }}

      - run: echo "PR number ${{ steps.digest-bot.outputs.pull_request_number }}"

      - name: Enable auto-merge
        if: ${{ steps.digest-bot.outputs.pull_request_number != '' }}
        run: gh pr merge --auto --squash "https://github.com/chainguard-dev/mono/pull/${{ steps.digest-bot.outputs.pull_request_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
