# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Publish

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write # For signing
      contents: read
      packages: write # For publishing images

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.6

      # Test building on pull requests.
      - if: github.event_name == 'pull_request'
        uses: chainguard-dev/actions/setup-registry@main
        with:
          port: 5000
      - if: github.event_name == 'pull_request'
        run: |
          echo KO_DOCKER_REPO=localhost:5000/kontext >> "$GITHUB_ENV"

      - run: |
          ko build --image-refs=ko.images --bare --platform=all ./cmd/expander

      # Sign the image when not a pull request.
      - if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919
        with:
          cosign-release: 'v2.0.2'
      - if: github.event_name != 'pull_request'
        run: |
          # shellcheck disable=SC2046
          cosign sign $(cat ko.images)
