# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write # For signing
      contents: read
      packages: write # For publishing images

    steps:
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.20.x'
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: ko-build/setup-ko@v0.7

      - run: ko build --image-refs=ko.images --bare --platform=all ./cmd/expander

      - uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0

      - run: |
          # shellcheck disable=SC2046
          cosign sign --yes $(cat ko.images)
