# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write # For signing
      contents: read
      packages: write # For publishing images

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20.x'
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: ko-build/setup-ko@v0.6

      - run: ko build --image-refs=ko.images --bare --platform=all ./cmd/expander

      - uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0

      - run: |
          # shellcheck disable=SC2046
          cosign sign --yes $(cat ko.images)
